name: Deploy React App to GitHub Pages
on:
  push:
    branches:
      - main  # Deploy when code is pushed to main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Use a compatible Node.js version

      - name: Install dependencies
        run: |
          cd path/to/your/project/root  # Navigate to the directory containing package.json
          npm install

      - name: Build React app with Vite
        run: |
         npm run build  # Navigate to the directory containing package.json
        working-directory: ./News_website

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist  # Correct path to Vite build output

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
