name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy when pushing to main

permissions:
  contents: write  # Required to push to gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Use a compatible Node.js version

      - name: Install dependencies
        run: npm install
        working-directory: ./News_website  # ✅ Run npm inside React folder

      - name: Build React app
        run: npm run build
        working-directory: ./News_website  # ✅ Ensure build runs in correct folder

      - name: Debug: Check if dist exists
        run: ls -la ./News_website/dist  # ✅ Debugging step

      - name: Deploy to gh-pages branch
        run: |
          npm install -g gh-pages
          npx gh-pages -d ./News_website/dist -b gh-pages
