name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Runs when changes are pushed to 'main'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Use a compatible Node.js version

      - name: Install dependencies
        run: npm install
        working-directory: ./News_website  # Ensures it runs inside your React app

      - name: Build React app
        run: npm run build
        working-directory: ./News_website  # Ensures build runs in the correct directory

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./News_website/build  # Correct path to React build output

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
