name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy when code is pushed to main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Use a compatible Node.js version

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: npm install
        working-directory: ./News_website

      - name: Build React app
        run: npm run build
        working-directory: ./News_website

      - name: Debug - List files
        run: ls -la ./News_website/dist
        shell: bash

      - name: Prepare deployment files
        run: |
          mkdir -p ./public
          cp -r ./News_website/dist/* ./public/
        shell: bash

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4